networks:
  frontend:
  backend: 
services:
  catalog:
    image: events/catalogapi
    build: 
      context: ./EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source = mssqlserver; Initial Catalog = EventDb; User Id=sa; Password=EventApi123(!); Connect Timeout = 30; Encrypt = False; Trust Server Certificate=False;"
      ExternalBaseurl: "https://localhost:7000"
      ASPNETCORE_HTTP_PORTS: 80
    ports: 
      - "7000:8080"
      
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment: 
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: EventApi123(!)
    ports:
      - "1448:1433" 
    container_name: eventscatalogsqlserver
    networks:
      - backend